baseURL = 'https://kantas-spike.github.io/portfolio/'
canonifyURLs = true

languageCode = 'ja-jp'
title = "kanta's spike"

theme = 'kantas'

copyright = "Â© 2022 kanta's spike"

publishDir = "docs"

[permalinks]
  blog = "/blog/:year/:month/:filename/"
  til = "/til/:year/:month/:filename/"

[security.exec]
  allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$', 'code']

[markup.highlight]
  noClasses = false
